version: "3.5"
services:
  odb1:
    image: orientdb
    command: dserver.sh
    container_name: tr-odb1
    volumes:
      - orientdb:/orientdb/databases
    environment:
      ORIENTDB_ROOT_PASSWORD: root # for local deployment keep it easy
      ORIENTDB_NODE_NAME: tr-odb1
    ports:
      - 2480:2480
      - 2424:2424
    networks:
     - kgai-network

networks:
  kgai-network:
    external: true
    name: kgai-network
    
volumes:
  orientdb:
