version: "3.5"
services:
  odb1:
    image: orientdb
    command: dserver.sh
    container_name: tr-odb1
    environment:
      ORIENTDB_ROOT_PASSWORD: ${ORIENTDB_ROOT_PASS}
      ORIENTDB_NODE_NAME: tr-odb1
    ports:
      - 2480:2480
      - 2424:2424
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: db.orientdb
