version: "3"
services:
  odb1:
    image: orientdb
    command: dserver.sh
    container_name: tr-odb1
    environment:
      ORIENTDB_ROOT_PASSWORD: root # for local deployment keep it easy
      ORIENTDB_NODE_NAME: tr-odb1
    ports:
      - 2480:2480
      - 2424:2424
