version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgresql_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=FoolishPassword
      - POSTGRES_USER=druid
      - POSTGRES_DB=druid
    networks:
      - kgai-network

  coordinator:
    image: apache/druid:0.18.0
    container_name: coordinator
    volumes:
      - coordinator_db:/opt/data
      - coordinator_var:/opt/druid/var
    depends_on:
      - postgres
    ports:
      # host:container
      - "8084:8084"
    command:
      - coordinator
    env_file:
      - environment
    networks:
      - kgai-network

  broker:
    image: apache/druid:0.18.0
    container_name: druid-broker
    volumes:
      - broker_var:/opt/druid/var
    depends_on:
      - postgres
      - coordinator
    ports:
      - "8082:8082"
    command:
      - broker
    env_file:
      - environment
    networks:
      - kgai-network

  historical:
    image: apache/druid:0.18.0
    container_name: historical
    volumes:
      - historical_db:/opt/data
      - historical_var:/opt/druid/var
    depends_on:
      - postgres
      - coordinator
    ports:
      - "8083:8083"
    command:
      - historical
    env_file:
      - environment
    networks:
      - kgai-network

  middlemanager:
    image: apache/druid:0.18.0
    container_name: middlemanager
    volumes:
      - middlemanager_db:/opt/data
      - middle_var:/opt/druid/var
    depends_on: 
      - postgres
      - coordinator
    ports:
      - "8091:8091"
    command:
      - middleManager
    env_file:
      - environment
    networks:
      - kgai-network

  router:
    image: apache/druid:0.18.0
    container_name: router
    volumes:
      - router_var:/opt/druid/var
    depends_on:
      - postgres
      - coordinator
    ports:
      - "8888:8888"
    command:
      - router
    env_file:
      - environment
    networks:
      - kgai-network

volumes:
  postgresql_db:
  middle_var:
  middlemanager_db:
  historical_var:
  historical_db:
  broker_var:
  coordinator_var:
  coordinator_db:
  router_var:

networks:
  kgai-network:
    external: true
    name: kgai-network