version: '3'
services:
  fluentd:
    image: fluentd:efk
    container_name: fluentd
    build:
      context: ./fluentd
    environment:
      FLUENTD_CONF: fluentd.conf
    volumes:
      - ./fluentd/conf/fluentd.conf:/fluentd/etc/fluentd.conf
    ports:
      - "9880:9880"
      - "24224:24224"
      - "24224:24224/udp"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: elasticsearch
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data01:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"

volumes:
  es-data01: /usr/local/es-data01