version: "3.5"
services:
  fluentd:
    image: knowledgeai/kgai-fluentd:0.0.1
    container_name: fluentd
    environment:
      FLUENTD_CONF: fluentd.conf
    ports:
      - "9880:9880"
      - "24224:24224"
      - "24224:24224/udp"
    networks:
     - kgai-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
     - kgai-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
     - kgai-network

networks:
  kgai-network:
    external: true
    name: kgai-network
