version: "3.5"
services:
  kgai-py-crawler:
    image: knowledgeai/kgai-py-crawler:1.2.1
    container_name: kgai-py-crawler
    # override parameters
    environment:
      KAFKA_BROKER: "broker:9092"
      KAFKA_SCHEMA: "http://schema-registry:8081"
      NEWS_TOPIC: corona
      SCRAPE_MONTH: "false"
      PARSE_ALL: "false"
      COMMON_CRAWL: "false"
      COMMON_CRAWL_DAYS_BACK: 30
      NEWS_CRAWL: "true"
      KAFKA_NEWS_RAW_TOPIC: "news-raw"
      # these should me mounted, check mounts below
      WARC_DOWNLOAD_DIR: "./CommonCrawl/WARC"
      ARTICLE_DOWNLOAD_DIR: "./CommonCrawl/Articles"
    networks:
      - kgai-network

  kgai-java-raw:
    image: knowledgeai/kgai-java-raw:1.0.0
    container_name: kgai-java-raw
    # override parameters
    environment:
      KAFKA_BROKER: "broker:9092"
      KAFKA_SCHEMA_REGISTRY: "http://schema-registry:8081"
      ORIENTDB_URL: "remote:odb1"
      KAFKA_NEWS_RAW_TOPIC: "newsRaw"
    networks:
      - kgai-network
  
  # kgai-py-basic-nlp:
  #   image: knowledgeai/kgai-py-basic-nlp:1.0.0
  #   container_name: kgai-py-basic-nlp
  #   # override parameters
  #   environment:
  #     KAFKA_BROKER: "broker:9092"
  #     KAFKA_SCHEMA: "http://schema-registry:8081"
  #     AVRO_NAMESPACE: "ai.knowledge.news.nlp"
  #     KAFKA_LISTEN_TOPIC: "news-raw"
  #     KAFKA_CONSUMER_ID: "news-nlp"
  #     KAFKA_PUBLISH_TOPC: "news-nlp"
  #     PUBLISH_NLP_KAFKA: "true"
  #   networks:
  #     - kgai-network

volumes:
  commoncrawl-data:

networks:
  kgai-network:
    external: true
    name: kgai-network
